# Generated by Django 5.2.8 on 2026-06-08 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0002_alter_chore_description"),
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "TASK"), _negated=True),
                    models.Q(("end_date__isnull", True), ("start_date__isnull", True)),
                    _connector="OR",
                ),
                name="chore_task_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "DUTY"), _negated=True),
                    models.Q(
                        ("due_date__isnull", True),
                        ("end_date__gte", models.F("start_date")),
                        ("end_date__isnull", False),
                        ("start_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chore_duty_dates_valid",
            ),
        ),
    ]
